name: Create Flutter Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      - name: Create Flutter project
        run: |
          flutter create .

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Initialize Flutter project" || echo "Nothing to commit"
          git push
