name: Universal Flutter APK Builder

on:
  workflow_dispatch:

  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Find APK
        run: |
          find build -type f -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-${{ github.run_number }}
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/**/**/*.apk
          if-no-files-found: error
